### ISSUE TITLE
Purpose for this repo?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/fraction-common-deprecated#2]
Found during code review https://github.com/phetsims/fractions-common/issues/29.

ReadMe.md is untouched since 5 years ago. Is there a reason why this repo is present or can we delete?

[phetsims/fraction-common](https://github.com/phetsims/fractions-common) is active and up-to-date to supplant this repo.

**Comment by Denz1994** [comment]
@jonathanolson mentioned in a zoom meeting: "It would be good to pass this by @ariel-phet to determine if this can be deleted or not." Initital commits date back to 2013 and most recent commits involve licensing updates. Tagging @ariel-phet.

**Comment by ariel-phet** [comment]
@jonathanolson @Denz1994 this looks like it was an initial MLL stab at working on the fractions sims. It can definitely be deleted.

**Comment by Denz1994** [comment]
Slack conversation 01/16/19:

> Denzell Barnett [2:13 PM]
> Hey JO, AP gave the okay to delete the “fractions-common-deprecated” repo.
> 
> Will deleting via Github cause any issues or aqua, yotta, or ct?

> Jonathan Olson [2:14 PM]
> I don't believe we really have links to it, and it's not in active-repos, so go ahead
> 
> 
> Denzell Barnett [2:14 PM]
> Roger. Deleting via Github.
